version: '3'

volumes:
  pgdata:

services:
  loan_api_db:
    image: "postgres:12.1-alpine"
    container_name: loan_api_db
    environment:
      - TZ=Asia/Almaty
      - POSTGRES_USER=loan_db_user
      - POSTGRES_PASSWORD=vj95GhjI0D5-Rrq06
      - POSTGRES_DB=loan
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  rabbimq:
    image: "rabbitmq:3-management-alpine"
    container_name: msg_broker
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "loan_user"
      RABBITMQ_DEFAULT_PASS: "LoanRabbitMQ1"
      RABBITMQ_DEFAULT_VHOST: "/loan-msg-broker"
