spring:
  application:
    name: Loan API
  profiles:
    active: local
    include:
      - security
  datasource:
    jdbc-url: 'jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:loan}?currentSchema=loan'
    username: '${DB_USERNAME:loan_db_user}'
    password: '${DB_PASSWORD:vj95GhjI0D5-Rrq06}'
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 600000
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
  flyway:
    schemas: 'loan'
    out-of-order: true
  redis:
    host: ${REDIS_HOST:localhost}
    timeout: 2000
    port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: 43200000
    type: redis
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: default
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_DEFAULT_USER:loan_user}
    password: ${RABBITMQ_DEFAULT_PASS:LoanRabbitMQ1}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST:/loan-msg-broker}
    listener:
      simple:
        defaultRequeueRejected: false

server:
  port: 8083
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics

logging:
  level:
    kz.codesmith.epay.loan.api.component.DocumentGenerator: WARN
    kz.codesmith.epay.security.component.JwtAuthorizationFilter: ERROR
    com.openhtmltopdf: ERROR

integration:
  pkb-connector:
    url: ${INTEGRATION_PKB_CONNECTOR_URL:http://localhost:8080/api}
    username: ${INTEGRATION_PKB_CONNECTOR_USERNAME:}
    password: ${INTEGRATION_PKB_CONNECTOR_PASSWORD:}
  telegram:
    url: ${TELEGRAM_GW_URL:http://localhost:8087/api}
    username: ${TELEGRAM_GW_USER:test}
    password: ${TELEGRAM_GW_PASS:test}
    service-timeout: ${TELEGRAM_GW_TIMEOUT:30000}
  acquiring:
    url: ${INTEGRATION_ACQUIRING_URL:https://cards-stage.pitech.kz}
    username: ${INTEGRATION_ACQUIRING_USERNAME:HAlza2msSvKJfp5QjH65IiUCtQ3Xsoo4}
    password: ${INTEGRATION_ACQUIRING_PASSWORD:0xRd1AAkQc4GAB3pv0JlLM2zAyKEleNj}
    connectTimeout: ${INTEGRATION_ACQUIRING_CONNECT_TIMEOUT:30000}
    readTimeout: ${INTEGRATION_ACQUIRING_READ_TIMEOUT:45000}
    paymentUrl: ${INTEGRATION_ACQUIRING_PAYMENT_URL:http://cards-stage.pitech.kz/gw/payments/cards/charge}
    successReturnUrl: ${INTEGRATION_ACQUIRING_SUCCESS_RETURN_URL:http://localhost:4200/cabinet/history}
    errorReturnUrl: ${INTEGRATION_ACQUIRING_ERROR_RETURN_URL:http://localhost:4200/cabinet/history}
    callbackSuccessUrl: ${ACQUIRING_SUCCESS_CALLBACK_URL:http://localhost:4200/cabinet/history}
    callbackErrorUrl: ${ACQUIRING_ERROR_CALLBACK_URL:http://localhost:4200/cabinet/history}
  payout:
    cardIdFrom: ${PAYOUT_CARD_FROM:card_-0I_7_Qw1aSqmjLGUFQ4p2gM_MijP6FK}
    enabled: ${PAYOUT_ENABLED:true}
    username: ${PAYOUT_USERNAME:admin}
    password: ${PAYOUT_PASSWORD:$2a$12$.ZDWXoeurdLU2.bJ/e74Feps0zj4xrUfA1NHLfyaMGHhYsHzmJjfK}
    callbackSuccessUrl: ${PAYOUT_SUCCESS_CALLBACK_URL:https://loan-stage.pitech.kz/api/payout/callback}
    callbackErrorUrl: ${PAYOUT_ERROR_CALLBACK_URL:https://loan-stage.pitech.kz/api/payout/callback}

jwt:
  secret: '${JWT_SECRET:A?D(G+KaPdSgVkYp3s6v9y$B&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u}'
  msToLive: ${JWT_MSTOLIVE:86400000}

scoring:
  useOwnScore: ${OWN_SCORE:true}
  enabled: ${SCORING_ENABLED:true}
  max-kdn: ${MAX_KDN:0.5}
  score-for-blacklist: ${SCORE_FOR_BLACK_LIST:620}
  badrate-for-blacklist: ${BADRATE_FOR_BLACK_LIST:14}
  max-decil: ${MAX_DECIL:10}
  interestRate: ${LOAN_INTERESTRATE:56}
  checkOpenLoans: ${CHECK_OPEN_LOANS:true}
  pdlMaxInterestRate: ${PDL_MAX_INTERESTRATE:24.5}
  maxScoringResult: ${MAX_SCORE:137160}


retrytemplate:
  maxAttempts: ${RETRYTEMPLATE_MAX_ATTEMPTS:3}
  backOffPeriod: ${RETRYTEMPLATE_MAX_ATTEMPTS:3000}

payment-services:
  plannedRePaymentProductId: ${PLANNED_REPAYMENT_PRODUCT_ID:1}
  partialRePaymentProductId: ${PARTIAL_REPAYMENT_PRODUCT_ID:2}
  totalRePaymentProductId: ${TOTAL_REPAYMENT_PRODUCT_ID:3}
  phone-verification:
    dummy-code: ${VERIFICATION_DUMMY:false}
    dummy-code-value: ${VERIFICATION_DUMMY_CODE:000000}
    code-length: ${VERIFICATION_CODE_LENGTH:6}
    wait-period-sec: ${VERIFICATION_WAIT_SEC:60}
    validity-period-min: ${VERIFICATION_VALID_MIN:30}
  coid-connector:
    url: 'http://${COID_CONNECTOR_HOST:coid-connector}:${COID_CONNECTOR_PORT:8080}/api'
    username: ${COID_CONNECTOR_USER:loan-api-user}
    password: ${COID_CONNECTOR_PASS:q}

loan-status-delay: ${WAIT_LOAN_STATUS_QUEUE_MESSAGE_DELAY:60000}
