package kz.codesmith.epay.loan.api.model.scoring;

public enum ScoringVars {
  MIN_SCORE_BALL,
  MAX_PD_BAD_RATE,
  FICO_SCORING,
  BEHAVIORAL_SCORING,
  MIN_RATE,
  MAX_GESV,
  MIN_LOAN_AMOUNT,
  MAX_LOAN_AMOUNT,
  MIN_LOAN_PERIOD,
  MAX_LOAN_PERIOD,
  ALT_AMOUNT_STEP,
  ALT_PERIOD_STEP,
  COST_OF_LIVING,
  OVERDUE_PERIOD,
  OVERDUE_AMOUNT
}
